version: '3.6'

services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db_nw
    ports:
      - 5432:5432

  wayfair_beer:
    restart: always
    build:
      context: .
      dockerfile: ./docker/wayfair_beer.dockerfile
    env_file:
      - .env
    environment:
      - HOST_FLASK_PORT=${HOST_FLASK_PORT}
      - UNTAPPD_CLIENT_ID=${UNTAPPD_CLIENT_ID}
      - UNTAPPD_CLIENT_SECRET=${UNTAPPD_CLIENT_SECRET}
      - VIRTUAL_HOST=${NGINX_PROXY_VIRTUAL_HOST}
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=${NGINX_PROXY_VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    ports:
      - 5000:5000
    volumes:
      - ./wayfair_beer:/wayfair_beer
      - ./alembic:/alembic
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
    links:
      - db:database
    command: ["python", "manage.py", "run"]

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/.certs/:/etc/nginx/certs:ro
      - nginx_proxy_vhost:/etc/nginx/vhost.d
      - nginx_proxy_html:/usr/share/nginx/html
    networks:
      - web_nw
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9.1
    networks:
      - web_nw
    volumes:
      - ~/.certs/:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_proxy_vhost:/etc/nginx/vhost.d
      - nginx_proxy_html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy


volumes:
  db:
  nginx_proxy_vhost:
  nginx_proxy_html:

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
