version: '3.6'

services:
  db:
    image: postgres:10
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db_nw
    ports:
      - 5432:5432

  wayfair_beer:
    restart: always
    build:
      context: .
      dockerfile: ./wayfair_beer/Dockerfile
    env_file:
      - .env
    environment:
      - HOST_FLASK_PORT=${HOST_FLASK_PORT}
      - UNTAPPD_CLIENT_ID=${UNTAPPD_CLIENT_ID}
      - UNTAPPD_CLIENT_SECRET=${UNTAPPD_CLIENT_SECRET}
    ports:
      - 5000:5000
    volumes:
      - ./wayfair_beer:/wayfair_beer
      - ./alembic:/alembic
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
    links:
      - db:database
    command: ["python", "manage.py", "run"]

  nginx:
    image: nginx:1.15
    env_file:
      - .env
    ports:
      - ${HOST_FLASK_PORT}:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - wayfair_beer

volumes:
  db:

networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
